### ISSUE TITLE
i cant find the shutdown sound.exe

### ISSUE THREAD

**Issue by Wugg-BIT** [erfg12/shutdownSound#1]
i cannot find the file shutdownsound.exe and i dont know why, is there something im doing wrong or something i could do?

**Comment by erfg12** [comment]
You need to provide more information. If you're compiling the code it would be under the debug or release folder.

Otherwise, the pre-compiled version is located under releases/assets on the GitHub project page. 

https://github.com/newagesoftwareLLC/shutdownSound/releases/download/1.01/Shutdown_Sound_Compiled.zip
